server.port=9001

# Configurations H2
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Création automatique des tables par Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true

# Encodage de data.sql
spring.sql.init.encoding=UTF-8

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Configuration externalisée
mes-configs.limitDeProduits=5
